/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "minifyjpeg.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 5, 0 };

img *
resize_image_1(img arg1,  CLIENT *clnt)
{
	static img clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RESIZE_IMAGE,
		(xdrproc_t) xdr_img, (caddr_t) &arg1,
		(xdrproc_t) xdr_img, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		//return (NULL);
		exit(124);
	}
	return (&clnt_res);
}
