/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MINIFYJPEG_H_RPCGEN
#define _MINIFYJPEG_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef struct {
	u_int img_len;
	char *img_val;
} img;

#define RESIZE_PROG 0x20000079
#define RESIZE_PROG_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define RESIZE_IMAGE 1
extern  img * resize_image_1(img , CLIENT *);
extern  img * resize_image_1_svc(img , struct svc_req *);
extern int resize_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define RESIZE_IMAGE 1
extern  img * resize_image_1();
extern  img * resize_image_1_svc();
extern int resize_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_img (XDR *, img*);

#else /* K&R C */
extern bool_t xdr_img ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MINIFYJPEG_H_RPCGEN */
